.FFFFFFFFFFFFFFFFFF
======================================================================
FAIL: test_treegen_in_tests_child_PID_not_found (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/31000/exe\n0' != '1'
+ 1- tests/31000/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_child_PID_not_found_build_continues (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/31003/exe\n0' != '1'
+ 1- tests/31003/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_child_exe_not_found (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/31001/exe\n0' != '1'
+ 1- tests/31001/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_child_exe_not_found_build_continues (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/31004/exe\n0' != '1'
+ 1- tests/31004/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_children_file_not_exist (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/51001/exe\n0' != '1'
+ 1- tests/51001/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_cmdline_args (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/41001/exe\n0' != '1'
+ 1- tests/41001/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_cmdline_empty (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/41002/exe\n0' != '1'
+ 1- tests/41002/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_cmdline_not_exist (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/51000/exe\n0' != '1'
+ 1- tests/51000/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_cmdline_path (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/41000/exe\n0' != '1'
+ 1- tests/41000/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_malloc_fails (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/25987/exe\n1' != '1'
- tests/25987/exe
  1

======================================================================
FAIL: test_treegen_in_tests_multiple_children_multiple_grandchildren (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/1123/exe\n0' != '1'
+ 1- tests/1123/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_multiple_children_no_grandchildren (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/30962/exe\n0' != '1'
+ 1- tests/30962/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_no_children (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/1234/exe\n0' != '1'
+ 1- tests/1234/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_one_child_one_grandchild (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/29462/exe\n0' != '1'
+ 1- tests/29462/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_one_child_only (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/25987/exe\n0' != '1'
+ 1- tests/25987/exe
- 0

======================================================================
FAIL: test_treegen_in_tests_pid_exe_not_found (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/25914/exe\n1' != '1'
- tests/25914/exe
  1

======================================================================
FAIL: test_treegen_in_tests_pid_not_found (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/99999/exe\n1' != '1'
- tests/99999/exe
  1

======================================================================
FAIL: test_treegen_in_tests_task_not_exist (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'tests/51002/exe\n0' != '1'
+ 1- tests/51002/exe
- 0

----------------------------------------------------------------------
Ran 19 tests in 0.561s

FAILED (failures=18)
